name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: isaquebrother90/isaquebrother90@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
